# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cf23e4a0-8ffe-4426-820b-0926ec490436'
  imageRepository: 'workerservice'
  containerRegistry: 'shehryarcid.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool: 
  name: azure-pool

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: Push stage
  jobs:
  - job: Build
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'


- stage: UpdateManifest
  displayName: 'Update Helm values with new image tag'
  dependsOn: Push   # or whatever your push stage is named
  jobs:
    - job: BumpTag
      steps:
        - checkout: none   # don't check out the current repo; we need the deployment repo instead

        - script: |
            git clone https://$(PAT_TOKEN)@dev.azure.com/shahshehryar80/voting-app/_git/voting-app-deployment-files.git
            cd voting-app-deployment-files

            git config user.email "pipeline@azuredevops.com"
            git config user.name "Azure Pipelines"

            # Update the tag in the values file for THIS service
            sed -i "s/^  tag: .*/  tag: \"$(Build.BuildId)\"/" myapp/worker-values.yaml

            git add myapp/values-aks.yaml
            git commit -m "Update voting-service image tag to $(Build.BuildId) [skip ci]"
            git push origin main
          displayName: 'Bump image tag and push to deployment repo'
          env:
            PAT_TOKEN: $(PAT_TOKEN)